stages:
  - deploy
  - publish

include:
  - remote: https://devops.mtra.in/tpl/v6/cdn/s3-upload.yml
  - remote: https://devops.mtra.in/tpl/v6/packages/gitlab-composer-publish.yml

publish-package:
  extends: .gitlab-composer-publish

upload-cdn:
  extends: .cdn-s3-upload
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - exists:
        - ".cdn/schemas/*"
